version: "3"

services:
  database:
    image: cassandra:latest
    container_name: chat-db
    hostname: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
    healthcheck:
      test: ["CMD", "cqlsh"]
      interval: 15s
      timeout: 10s
      retries: 10

  server:
    image: python:3.12-slim
    container_name: chat-server
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      database:
        condition: service_healthy
    command: bash -c "
      pip install -r requirements.txt &&
      cd server &&
      uvicorn main:app --host 0.0.0.0 --port 5000 --reload"
    ports:
      - "5000:5000"

  web:
    image: nginx:latest
    container_name: chat-web
    volumes:
      - ./www/:/usr/share/nginx/html
    ports:
      - "80:80"
    restart: always
