services:
  database:
    image: cassandra:latest
    container_name: chat-db
    hostname: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
    healthcheck:
      test: ["CMD", "cqlsh"]
      interval: 15s
      timeout: 10s
      retries: 10

  cache:
    image: valkey/valkey:latest
    container_name: chat-cache
    volumes:
      - "./conf/valkey.conf:/etc/valkey/valkey.conf"
      - "./data/valkey/:/var/lib/valkey"
    ports:
      - "6379:6379"
    command: ["valkey-server", "/etc/valkey/valkey.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]

  server:
    image: python:3.12-slim
    container_name: chat-server
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    command: bash -c "
      pip install -r requirements.txt &&
      cd server &&
      uvicorn main:app --host 0.0.0.0 --port 5000 --reload"
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "pytest", "--version"]
      interval: 30s
      timeout: 10s
      retries: 20

  web:
    image: nginx:latest
    container_name: chat-web
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - ./www/:/usr/share/nginx/html
    ports:
      - "80:80"
    restart: always
